package com.example.linkedus.Model;

public class ExData {

    String imageUrl = "https://xsgames.co/randomusers/avatar.php?g=male";
    String names[] = {
            "Aarav Patel",
            "Sanya Singh",
            "Arjun Sharma",
            "Isha Gupta",
            "Rohan Verma",
            "Anaya Chopra",
            "Aryan Kumar",
            "Diya Malhotra",
            "Karan Mittal",
            "Pooja Bose"};//47 elements

    String professions[][] = {
            {   "Software Developer",  "Designs and develops software applications, websites, and systems." },
            {   "Doctor",  "Diagnoses and treats illnesses, provides medical care to patients." },
            {   "Teacher",  "Educates and instructs students in various subjects and grade levels." },
            {   "Graphic Designer",  "Creates visual concepts and designs for print, digital media, and advertising." },
            {   "Accountant",  "Manages financial records, prepares and analyzes financial reports." },
            {   "Mechanical Engineer",  "Designs and develops mechanical systems and devices." },
            {   "Marketing Manager",  "Plans and executes marketing strategies to promote products or services." },
            {   "Nurse",  "Provides medical care, administers medications, and supports patient well-being." },
            {   "Electrician",  "Installs, maintains, and repairs electrical systems and components." },
            {   "Chef",  "Prepares and cooks food in various settings, such as restaurants or hotels." },
            {   "Lawyer",  "Provides legal advice, represents clients in legal matters, and prepares legal documents." },
            {   "Data Scientist",  "Analyzes and interprets complex data sets to inform business decisions." },
            {   "Architect",  "Designs and plans buildings, ensuring functionality, safety, and aesthetics." },
            {   "Psychologist",  "Studies and analyzes human behavior, providing mental health support and therapy." },
            {   "Civil Engineer",  "Plans, designs, and oversees the construction of infrastructure projects." },
            {   "Biomedical Scientist",  "Conducts research to understand diseases and develop medical treatments." },
            {   "Pilot",  "Operates aircraft, ensuring safe and efficient flights for passengers or cargo." },
            {   "Environmental Scientist",  "Studies the environment, assessing and managing its impact on ecosystems." },
            {   "Fashion Designer",  "Creates clothing and accessory designs, following fashion trends." },
            {   "Physical Therapist",  "Helps patients recover from injuries or surgeries through physical exercises and therapies." },
            {   "Police Officer",  "Maintains public order, enforces laws, and ensures community safety." },
            {   "Social Worker",  "Assists individuals and families in need, providing support and connecting them with resources." },
            {   "Web Developer",  "Builds and maintains websites, ensuring functionality and user experience." },
            {   "Mechanical Technician",  "Assists in the installation, maintenance, and repair of mechanical systems and equipment." },
            {   "Financial Analyst",  "Analyzes financial data, prepares reports, and provides insights for investment decisions." },
            {   "Marine Biologist",  "Studies marine life and ecosystems, conducting research to protect and preserve oceans." },
            {   "Speech-Language Pathologist",  "Assesses and treats speech and language disorders in individuals of all ages." },
            {   "Interior Designer",  "Plans and creates functional and aesthetically pleasing interior spaces." },
            {   "Mathematician",  "Applies mathematical principles to solve problems and make informed decisions." },
            {   "Human Resources Manager",  "Manages personnel, recruitment, and employee relations within an organization." },
            {   "Pharmacist",  "Dispenses medications, provides drug information, and ensures patient safety." },
            {   "Meteorologist",  "Studies and forecasts weather patterns, providing information for planning and safety." },
            {   "Veterinarian",  "Diagnoses and treats illnesses in animals, ensuring their well-being." },
            {   "Journalist",  "Investigates and reports news stories through various media channels." },
            {   "Air Traffic Controller",  "Manages and coordinates air traffic to ensure safe and efficient aircraft movement." },
            {   "Geologist",  "Studies the Earth's structure, composition, and processes, including mineral and energy resources." },
            {   "Emergency Medical Technician (EMT)",  "Provides emergency medical care and transportation to individuals in critical situations." },
            {   "Occupational Therapist",  "Assists individuals in regaining daily living skills after illness or injury." },
            {   "Robotics Engineer",  "Designs and builds robotic systems for various applications, from manufacturing to healthcare." },
            {   "Sociologist",  "Studies human society, behavior, and social institutions to understand and address social issues." },
            {   "IT Security Analyst",  "Protects computer systems and networks from security breaches and cyber threats." },
            {   "Airline Pilot",  "Flies aircraft for airlines, ensuring the safety and comfort of passengers." },
            {   "Librarian",  "Manages library resources, assists patrons, and promotes literacy and learning." },
            {   "Speechwriter",  "Writes speeches for individuals, such as politicians, executives, or public figures." },
            {   "Urban Planner",  "Develops plans and programs for land use in urban areas, considering infrastructure and community needs." },
            {   "Biotechnologist",  "Applies biological principles and techniques to develop products and technologies." },
            {   "Network Administrator",  "Manages and maintains computer networks, ensuring smooth communication and data flow." },
            {   "Firefighter",  "Responds to fires and emergencies, providing rescue and medical assistance." },
            {   "Civil Rights Attorney",  "Advocates for individuals' civil rights and fights against discrimination and injustice." },
            {   "Game Developer",  "Creates and designs video games, programming and developing interactive experiences." },
            {   "Dental Hygienist",  "Assists dentists in oral care procedures and educates patients on dental hygiene practices." },
            {   "Political Scientist",  "Studies political systems, institutions, and behavior to analyze and understand political phenomena." },
            {   "Tour Guide",  "Leads tours, providing information and insights about historical, cultural, or natural attractions." },
            {   "Forensic Scientist",  "Applies scientific methods to investigate and analyze evidence in criminal cases." },
            {   "Market Research Analyst",  "Studies market conditions to identify potential sales opportunities for products and services." },
            {   "Dietitian",  "Promotes healthy eating habits, creates nutrition plans, and advises on dietary choices." },
            {   "Physiotherapist",  "Assesses and treats physical injuries or disabilities using therapeutic exercises and interventions." },
            {   "Environmental Engineer",  "Develops solutions to environmental issues, such as pollution and waste management." },
            {   "Forestry Technician",  "Assists in the management and conservation of forests, monitoring tree health and growth." },
            {   "Translator",  "Converts written or spoken content from one language to another, preserving the intended meaning." },
            {   "Fitness Trainer",  "Guides individuals in physical exercises, providing fitness and health advice." },
            {   "Phlebotomist",  "Collects blood samples from patients for medical testing and donation purposes." },
            {   "Surveyor",  "Measures and maps land and property boundaries for construction and development projects." },
            {   "IT Consultant",  "Advises organizations on information technology strategies and solutions." },
            {   "Civil Rights Activist",  "Advocates for equal rights and social justice, addressing issues of discrimination and inequality." },
            {   "Emergency Dispatcher",  "Coordinates emergency response services, dispatching help to those in need." },
            {   "Radiographer",  "Operates imaging equipment to capture medical images for diagnosis and treatment." },
            {   "Solar Energy Technician",  "Installs and maintains solar panels and systems to harness solar energy." },
            {   "Video Game Designer",  "Creates concepts and designs for video games, including characters, levels, and gameplay mechanics." },
            {   "Academic Advisor",  "Guides students in their academic and career decisions, providing advice and support." },
            {   "Historian",  "Studies and interprets historical events, periods, and cultures." },
            {   "Social Media Manager",  "Manages and develops content for social media platforms to enhance brand visibility." },
            {   "Meteorological Technician",  "Assists meteorologists in collecting and analyzing weather data." },
            {   "Epidemiologist",  "Studies the patterns and causes of diseases in populations to inform public health strategies." },
            {   "Bricklayer",  "Constructs walls and structures using bricks, concrete blocks, or other masonry materials." },
            {   "Speech Pathologist",  "Assesses and treats communication and swallowing disorders in individuals of all ages." },
            {   "Solar Panel Installer",  "Installs and maintains solar panels and systems to generate renewable energy." },
            {   "HR Specialist",  "Specializes in specific areas of human resources, such as recruitment, training, or benefits administration." },
            {   "Cryptocurrency Analyst",  "Analyzes and monitors trends in the cryptocurrency market, providing insights for investors." },
            {   "Tax Consultant",  "Advises individuals and businesses on tax-related matters and helps with tax planning." },
            {   "Flight Attendant",  "Ensures the safety and comfort of passengers during flights, providing customer service." },
            {   "Fashion Stylist",  "Creates visually appealing outfits and looks for individuals or events." },
            {   "Marine Engineer",  "Designs and maintains marine vessels and structures, ensuring their functionality and safety." },
            {   "Renewable Energy Engineer",  "Designs and develops systems for harnessing renewable energy sources." },
            {   "Technical Writer",  "Creates documentation and instructional materials for technical products and processes." },
            {   "Astronomer",  "Studies celestial bodies, galaxies, and the universe to understand their origins and behavior." },
            {   "Materials Engineer",  "Develops materials with specific properties for use in various industries." },
            {   "Aquaculturist",  "Cultivates and harvests aquatic organisms, such as fish or shellfish, for commercial purposes." },
            {   "UX/UI Designer",  "Designs user interfaces and experiences for digital products, focusing on usability and aesthetics." },
            {   "Sports Coach",  "Instructs and trains athletes in specific sports, focusing on skill development and strategy." },
            {   "Political Campaign Manager",  "Organizes and manages political campaigns, coordinating strategies and activities." },
            {   "Fire Investigator",  "Investigates the causes of fires and explosions, determining if foul play was involved." },
            {   "Quality Assurance Analyst",  "Ensures the quality and functionality of products or services through testing and analysis." },
            {   "Zoologist",  "Studies animal behavior, ecology, and classification to contribute to wildlife conservation." },
            {   "Ethical Hacker",  "Identifies and addresses security vulnerabilities in computer systems to improve cybersecurity." },
            {   "Event Planner",  "Coordinates and plans events, such as weddings, conferences, or parties." },
            {   "Network Engineer",  "Designs, implements, and manages computer networks for organizations." },
            {   "Forensic Accountant",  "Investigates financial discrepancies and fraud for legal and investigative purposes." },
            {   "Archaeologist",  "Studies human history through the excavation and analysis of artifacts and structures." },
            {   "Clinical Psychologist",  "Assesses and treats mental health disorders through therapy and counseling." },
            {   "Risk Analyst",  "Analyzes and assesses potential risks to help organizations make informed decisions." },
            {   "Biomedical Engineer",  "Designs and develops medical equipment and technologies to improve healthcare." },
            {   "Cartographer",  "Creates maps and charts to represent geographical features and information." },
            {   "Podiatrist",  "Diagnoses and treats foot and ankle conditions, providing medical care and surgery." },
            {   "Animal Behaviorist",  "Studies and analyzes the behavior of animals, addressing behavioral issues and improving welfare." },
            {   "GIS Analyst",  "Uses Geographic Information Systems (GIS) to analyze and interpret spatial data." },
            {   "Genetic Counselor",  "Provides information and support to individuals and families regarding genetic conditions and testing." },
            {   "Interior Architect",  "Designs and plans interior spaces, considering both aesthetic and functional aspects." },
            {   "Cryptocurrency Developer",  "Creates and maintains blockchain-based applications and cryptocurrencies." },
            {   "Speech and Debate Coach",  "Trains students in public speaking and debate skills for academic competitions." },
            {   "Ethnographer",  "Studies and documents the cultures and practices of specific groups of people." },
            {   "Water Resources Engineer",  "Manages and develops water-related projects, ensuring sustainable use and conservation." },
            {   "Microbiologist",  "Studies microscopic organisms, such as bacteria and viruses, to understand their biology and behavior." },
            {   "Legal Mediator",  "Facilitates negotiations and resolves disputes between parties through mediation." },
            {   "Financial Planner",  "Assists individuals and businesses in creating and implementing financial plans." }
    };

    String company[] = {
            "Hometown Hardware",
            "Community Catering Co.",
            "LocalTech Solutions",
            "Neighborly Builders",
            "Cityscape Realty",
            "Village Bookstore",
            "Town Square Pharmacy",
            "Metro Grocers",
            "Harborview Consulting",
            "Heritage Bakery"};//47 element

    int num[] = {
            123, 456, 789, 234, 567,
            890, 321, 654, 987, 876,
            543, 210, 345, 678, 901,
            432, 765, 876, 234, 567,
            890, 123, 456, 789, 987,
            654, 321, 234, 567, 890,
            543, 876, 789, 210, 345,
            678, 901, 432, 765, 876,
            123, 234, 567, 890, 321,
            654, 987, 876, 543, 210};

    String address[] = {
            "123 Main Street, Sector 1, Cityville, Delhi",
            "456 Park Avenue, Raj Nagar, Townsville, Mumbai",
            "789 Green Road, Shivaji Nagar, Garden City, Bangalore",
            "101 Sunshine Lane, Jubilee Hills, Metropolis, Hyderabad",
            "234 Riverfront Drive, Marine Lines, Harbor City, Kolkata",
            "567 Hillside Avenue, Civil Lines, Riverside, Chennai",
            "890 Lakeside Road, Model Town, Lakeshore, Ahmedabad",
            "202 Silver Crescent, Cantonment, Silver City, Pune",
            "345 Valley View, Panjim Peth, Hilltop, Goa",
            "678 Skyline Street, Gomti Nagar, Horizon City, Lucknow"};//47 element



}
